services:
  - type: web
    name: safetrace-ai
    runtime: docker
    dockerfilePath: ./ai-service/Dockerfile
    dockerContext: ./ai-service
    plan: free
    region: frankfurt
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
